### ISSUE TITLE
TODO: formal form for working correctly with github 

### ISSUE THREAD

**Issue by EmiliaZorin** [AvielCo/SmartScript#7]
- [x] rules to open an issue
- [x] rules for PR
- [x] define scrum master role

**Comment by SoloNoah** [comment]
my bad. should have opened a PR for this issue instead of commit straight to the repo.
anyway, did the first 2 tasks. its in `pr_issues.md` file. we need to understand now how to define the scrum master role.
